### ISSUE TITLE
/reservations/_id/check で RESERVATION_NOT_FOUND が返ってこない

### ISSUE THREAD

**Issue by su8ru** [afes-website/cappuccino-back#49]
ほかにもありそう……

**Comment by Takeno-hito** [comment]
ねえ 変えたって言ってたけど変わってないじゃん
https://github.com/afes-website/docs/blob/develop/src/apis/reservations/_id%40string/index.ts

**Comment by Takeno-hito** [comment]
error_code を返してるのは 404 だと何か判別がつかないから補足で返している という理由なので、reservation に関しては 404 で問題ないという話でこうなってるけど back じゃなくて docs に issue 移していいですか
