### ISSUE TITLE
エラー各種をログに残す

### ISSUE THREAD

**Issue by su8ru** [afes-website/cappuccino-back#54]
500 とかのエラーをはじめとした、400 とかも含むエラー各種

**Comment by ibuki2003** [comment]
ただ重要度を5段階評価すればいいってもんじゃないと思うんです verbosityと比較する程度の意味合いしかないので
500番台をerror、他をinfoとかで分けるほうがすきです

**Comment by ibuki2003** [comment]
ログに残す*エラー*はアプリケーションのエラーで要修正なものであるべきで、その観点で500系以外をerror以上に上げたくない
高くてもwarnだけど、404とか403でwarnなのはどうかと思います…
参考文献: https://engineering.otobank.co.jp/entry/2016/09/20/181756
